In [1]:
import  numpy as numpy
import pandas as pd

<h3>Creating a Dataframe</h3>

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
#list
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [9]:
#but if you want to print column name also then you should perform this 
columns= ["Name", "Age", "City", "Salary"]
df2= pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

<h3>Selecting and Indexing of columns</h3>

In [10]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [13]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

<h3>Creating a new Column.</h3>

In [14]:

df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [15]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

<h3>Remove Column</h3>

In [22]:
#Axis 0 means horizontal and 1 means vertical
df2.drop("City", axis=1)

    Name  Age  Salary Designation
0   John   28   65000      Doctor
1   Anna   34   70000        Eng.
2  Peter   29   62000      Doctor
3  Linda   42   85000        Eng.

In [27]:
df2.drop("Designation", axis=1)
#drop only remove and show copy of frame not originally delete original frame

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2
#but it show all column insist of droping it

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [30]:
#what can you do , it can delete from main data also 
df2.drop("Designation", axis=1, inplace = True)

In [32]:
df2
#now you can see data designation is originally delete from main frame

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
#we can also drop row , so we see as 
df2.drop(0,axis= 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [34]:
#but it doesnot originally delete
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

<h3>Selecting Rows</h3>

In [35]:
#for selecting a row , we used loc()
df2.loc[[0]]

   Name  Age      City  Salary
0  John   28  New York   65000

In [36]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [37]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

<h3>Selecting Subsets of Rows and Columns </h3>

In [38]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [39]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

<h3> Conditional Selection</h3>

In [40]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
#I only want to see those people whose age is above 30
df[df["Age"]> 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [43]:
#I only want poeple whose age is above 30 and their city must be paris
df[(df["Age"]>30) & (df["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000