In [1]:
import numpy as np
import pandas as pd

<h3> Finding Missing Data</h3>

In [3]:
#np.nan means it have NULL value
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
df.isna()#is there is any null value if yes then return True and otherwise False

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [6]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

<h3>Removing Missing Data</h3>

In [7]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [8]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [10]:
df.dropna(thresh=3)#thresh means you must have to contain that much amounnt of ono null value that satisfy

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

<h3>Filling The Missing Data</h3>

In [11]:
df.fillna(0)#those value have null value which now contain 0 value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [13]:
df#All change i made are not seen it df because we doesnot apply inplace

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [16]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)
#different value are place that different null

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [20]:
df.fillna(df.mean())#filling null value with means value of their respected column

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0